# **  WGCNA pipeline part 2:   **

# choose soft threshold
# build scale-free network

# ###### input: ###########################################################
# samplTree.Rdata generated by WGCNA_part2.R
###########################################################################


## module load R/3.6.1
# .libPaths("/u/juxiao/R/x86_64-pc-linux-gnu-library/3.6" )
# .libPaths()

cat("\n
    *********************************\n
    *********  WGCNA part2  *********\n
    ** Test Scale-free topology *****\n
    *********************************")

library(ggplot2)
library(gplots)
library(reshape2)
library(doParallel)
library(WGCNA)
options(stringsAsFactors = FALSE)

directory = commandArgs(trailingOnly=TRUE)[1]
cutHeight = commandArgs(trailingOnly=TRUE)[2]

setwd(file.path(directory))
getwd()


## Load the data saved in the first part
cat("\n------------- Loading sample clustring data --------------------\n")
lnames = load("sampleTree.Rdata")
# lnames


## cut sample tree
if (is.na(cutHeight)) {
    cat("No cutHeight provided, will keep all the samples\n")
    cutHeight = max(sampleTree$height)*1.05  # make the cut line higher than all branches
}else{
    cat("Cut sample tree at ", cutHeight)
    cutHeight = as.numeric(cutHeight)
}


## Plot sample tree with cut line
pdf("Part2_SampleClustering_cut.pdf", width=12, height=8)
par(cex = 0.6)
par(mar = c(1,6,2,1))
plot(sampleTree, main = "Sample clustering", sub="", xlab="", cex.lab = 1.5,
     cex.axis = 1.5, cex.main = 2)
abline(h = cutHeight, col = "red");
invisible(dev.off())


## Determine cluster under the line
clust = cutreeStatic(sampleTree, cutHeight = cutHeight, minSize = 10)
table(clust)
## choose the cluster with the biggest numbers of samples
keepSamples = (clust== names(which.max(table(clust))))

datExpr2 = datExpr1[keepSamples, ]
datTraits = datTraits[keepSamples, ] 

outlierSamples <- !keepSamples
outlierSamples_names<- rownames(datExpr1[!keepSamples, ])
cat("Romved outlier samples: \n")
cat( outlierSamples_names)

## Re-cluster samples
cat("\n\n------------------- Recalculate sampleTree ------------------- \n")
sampleTree2 = hclust(dist(datExpr2), method = "average")
## add trait heatmap:  white--low, red--high, grey--missing
traitColors = numbers2colors(datTraits, signed = FALSE)

## Plot the sample dendrogram and trait heatmap
pdf("Part2_SampleDendrogram.pdf", width=12, height=8)
plotDendroAndColors(sampleTree2, traitColors,
                    groupLabels = names(datTraits), 
                    main = "Sample dendrogram and trait heatmap")
invisible(dev.off())


############ network construction (soft-threshold ) ####################

cat("\n------------------- network topology analysis ------------------- \n ")

## Choose a set of soft-thresholding powers
powers = c(c(1:10), seq(from = 12, to=20, by=2))

## parallize if possible
registerDoParallel()

## Call the network topology analysis function
## **********  55000 genes ~ 1 hour *********
## **********  16000 genes ~ 10 minutes ******
sft = pickSoftThreshold(datExpr2, powerVector = powers, verbose = 5)


# # save plot as png and pdf 
# png("Part2_ScaleFreeTopology.png", width=1000, height=500)
# par(mfrow = c(1,2))
# cex1 = 0.9
# plot(sft$fitIndices[,1], -sign(sft$fitIndices[,3])*sft$fitIndices[,2],
#      xlab="Soft Threshold (power)",ylab="Scale Free Topology Model Fit,signed R^2",type="n",
#      main = paste("Scale independence"));
# text(sft$fitIndices[,1], -sign(sft$fitIndices[,3])*sft$fitIndices[,2],
#      labels=powers,cex=cex1,col="red");
# plot(sft$fitIndices[,1], sft$fitIndices[,5],
#      xlab="Soft Threshold (power)",ylab="Mean Connectivity", type="n",
#      main = paste("Mean connectivity"))
# text(sft$fitIndices[,1], sft$fitIndices[,5], labels=powers, cex=cex1,col="red")


pdf("Part2_ScaleFreeTopology.pdf", width=12, height=8)
par(mfrow = c(1,2))
cex1 = 0.9
plot(sft$fitIndices[,1], -sign(sft$fitIndices[,3])*sft$fitIndices[,2],
     xlab="Soft Threshold (power)",ylab="Scale Free Topology Model Fit,signed R^2",type="n",
     main = paste("Scale independence"));
text(sft$fitIndices[,1], -sign(sft$fitIndices[,3])*sft$fitIndices[,2],
     labels=powers,cex=cex1,col="red");
plot(sft$fitIndices[,1], sft$fitIndices[,5],
     xlab="Soft Threshold (power)",ylab="Mean Connectivity", type="n",
     main = paste("Mean connectivity"))
text(sft$fitIndices[,1], sft$fitIndices[,5], labels=powers, cex=cex1,col="red")
invisible(dev.off())


save(datExpr2, datTraits, powers, sft,  file = "topology.Rdata")
cat("\n--------------------- Part2 Done -----------------------------\n")

