# **  WGCNA pipeline part 2:   **

# offer topology information for soft threshold choosing

# ###### input: ###########################################################
# samplTree.Rdata generated by WGCNA_part2.R
###########################################################################


## module load R/3.6.1
# .libPaths("/u/juxiao/R/x86_64-pc-linux-gnu-library/3.6" )
# .libPaths()

cat("\n
    *********************************\n
    *********  WGCNA part2  *********\n
    ** Test Scale-free topology *****\n
    *********************************")

library(ggplot2)
library(gplots)
library(reshape2)
library(doParallel)
library(WGCNA)
options(stringsAsFactors = FALSE)

directory = commandArgs(trailingOnly=TRUE)[1]
cutHeight = as.numeric(commandArgs(trailingOnly=TRUE)[2])



setwd(file.path(directory))
getwd()


# Load the data saved in the first part
cat("\n------------- Loading sample clustring data --------------------\n")
lnames = load("sampleTree.Rdata")
# lnames

# decide cut hight
# ------------------------ choose cut hight of samples -------------------
# cat("\nEnter the hight to cut outliers 
#     \n(Please consult Part1_SampleClustering.pdf to decide cutting height ): ")
# cutHeight = as.numeric(readLines("stdin", 1))

cat("cut height: ", cutHeight)


# Plot the sample tree
pdf("Part2_SampleClustering_cut.pdf", width=12, height=8)
par(cex = 0.6)
par(mar = c(1,6,2,1))
plot(sampleTree, main = "Sample clustering", sub="", xlab="", cex.lab = 1.5,
     cex.axis = 1.5, cex.main = 2)
# Plot the cut line
abline(h = cutHeight, col = "red");
dev.off()


# Determine cluster under the line
clust = cutreeStatic(sampleTree, cutHeight = cutHeight, minSize = 10)
table(clust)

# choose the cluster with the biggest numbers of samples
keepSamples = (clust== names(which.max(table(clust))))

datExpr2 = datExpr1[keepSamples, ]
datTraits = datTraits[keepSamples, ] 

outlierSamples <- !keepSamples
outlierSamples_names<- rownames(datExpr1[!keepSamples, ])
# outlierSamples_names
cat("Romved outlier samples: \n")
cat( outlierSamples_names)

# Re-cluster samples
cat("\n\n------------------- Recalculate sampleTree ------------------- \n")
sampleTree2 = hclust(dist(datExpr2), method = "average")
# Convert traits to a color representation: white means low, red means high, grey means missing entry
traitColors = numbers2colors(datTraits, signed = FALSE)

# Plot the sample dendrogram and the colors underneath
pdf("Part2_SampleDendrogram.pdf", width=12, height=8)
plotDendroAndColors(sampleTree2, traitColors,
                    groupLabels = names(datTraits), 
                    main = "Sample dendrogram and trait heatmap")
dev.off()


############ network construction (soft-threshold selection) #########

cat("\n---------------------Select soft-threshold--------------------\n ")

# Choose a set of soft-thresholding powers
powers = c(c(1:10), seq(from = 12, to=20, by=2))

# parallize if possible
registerDoParallel()

# Call the network topology analysis function
# **********  55000 genes ~ 1 hour *********
# **********  16000 genes ~ 10 minutes ******
sft = pickSoftThreshold(datExpr2, powerVector = powers, verbose = 5)


# # save plot as png and pdf 
# png("Part2_ScaleFreeTopology.png", width=1000, height=500)
# par(mfrow = c(1,2))
# cex1 = 0.9
# plot(sft$fitIndices[,1], -sign(sft$fitIndices[,3])*sft$fitIndices[,2],
#      xlab="Soft Threshold (power)",ylab="Scale Free Topology Model Fit,signed R^2",type="n",
#      main = paste("Scale independence"));
# text(sft$fitIndices[,1], -sign(sft$fitIndices[,3])*sft$fitIndices[,2],
#      labels=powers,cex=cex1,col="red");
# plot(sft$fitIndices[,1], sft$fitIndices[,5],
#      xlab="Soft Threshold (power)",ylab="Mean Connectivity", type="n",
#      main = paste("Mean connectivity"))
# text(sft$fitIndices[,1], sft$fitIndices[,5], labels=powers, cex=cex1,col="red")


pdf("Part2_ScaleFreeTopology.pdf", width=12, height=8)
par(mfrow = c(1,2))
cex1 = 0.9
plot(sft$fitIndices[,1], -sign(sft$fitIndices[,3])*sft$fitIndices[,2],
     xlab="Soft Threshold (power)",ylab="Scale Free Topology Model Fit,signed R^2",type="n",
     main = paste("Scale independence"));
text(sft$fitIndices[,1], -sign(sft$fitIndices[,3])*sft$fitIndices[,2],
     labels=powers,cex=cex1,col="red");
plot(sft$fitIndices[,1], sft$fitIndices[,5],
     xlab="Soft Threshold (power)",ylab="Mean Connectivity", type="n",
     main = paste("Mean connectivity"))
text(sft$fitIndices[,1], sft$fitIndices[,5], labels=powers, cex=cex1,col="red")
dev.off()


save(datExpr2, datTraits, powers, sft,  file = "topology.Rdata")
cat("\n--------------------- Part2 Done -----------------------------\n")