# **  WGCNA pipeline part 3:   **

# choose soft threshold power to creat scale-free network; module detection: module-traits correlation

# ###### input: ###########################################################
# topology.Rdata generated by WGCNA_part2.R
###########################################################################


## module load R/3.6.1
.libPaths("/u/juxiao/R/x86_64-pc-linux-gnu-library/3.6" )
.libPaths()

cat("\n
    *********************************\n
    *********  WGCNA part3  *********\n
    ******* Module detection ********\n
    *********************************")

library(ggplot2)
library(gplots)
library(reshape2)
library(doParallel)
library(WGCNA)
options(stringsAsFactors = FALSE)


cat("Enter working directory \nLocation of \"topology.RData\": ")
directory <- readLines("stdin", 1)

setwd(file.path(directory))
getwd()


# Load the data saved in the second part
lnames = load("topology.Rdata")
# lnames


# decide soft threshold power
cat("\nEnter the soft threshold power to use
    \n(Please consult Part2_ScaleFreeTopology.pdf to decide ): ")

sft.power <- ""
while (!(sft.power %in% c(1:20))) {
  sft.power = as.numeric(readLines("stdin", 1))
  if (!(sft.power %in% c(1:20))) { 
    cat("Chosen power is out of range\n(Please consult ScaleFree_topology.pdf/png to decide ):")}
}


# replot the topology results:
pdf("Part3_ScaleFreeTopology_sft.pdf", width=12, height=8)
par(mfrow = c(1,2))
cex1 = 0.9
# Scale-free topology fit index as a function of the soft-thresholding power
plot(sft$fitIndices[,1], -sign(sft$fitIndices[,3])*sft$fitIndices[,2],
     xlab="Soft Threshold (power)",ylab="Scale Free Topology Model Fit,signed R^2",type="n",
     main = paste("Scale independence"));
text(sft$fitIndices[,1], -sign(sft$fitIndices[,3])*sft$fitIndices[,2],
     labels=powers,cex=cex1,col="red")
abline(h=-sign(sft$fitIndices[sft.power,3])*sft$fitIndices[sft.power,2],col="red")

# Mean connectivity as a function of the soft-thresholding power
plot(sft$fitIndices[,1], sft$fitIndices[,5],
     xlab="Soft Threshold (power)",ylab="Mean Connectivity", type="n",
     main = paste("Mean connectivity"))
text(sft$fitIndices[,1], sft$fitIndices[,5], labels=powers, cex=cex1,col="red")
abline(h=sft$fitIndices[sft.power,5],col="red")
dev.off()


# use WGCNA's cor() function
cat("\n---------------------module detection--------------------\n")
cat("\n**This may take hours with large numbers of genes and samples**\n")

cor <- WGCNA::cor
net = blockwiseModules(datExpr2, power = sft.power,
                       TOMType = "unsigned", minModuleSize = 30,
                       reassignThreshold = 0, mergeCutHeight = 0.25,
                       numericLabels = TRUE, pamRespectsDendro = FALSE,
                       saveTOMs = TRUE,
                       saveTOMFileBase = "moduleDetection", 
                       verbose = 3)
cor<-stats::cor
# table(net$colors) 

cat("\n---------------finish detecting modules--------------------\n")

mergedColors = labels2colors(net$colors)

# Plot the dendrogram and the module colors underneath
pdf("Part3_GeneClusterDendrogram.pdf", width=12, height=8)
plotDendroAndColors(net$dendrograms[[1]], mergedColors[net$blockGenes[[1]]],
                    "Module colors",
                    dendroLabels = FALSE, hang = 0.03,
                    addGuide = TRUE, guideHang = 0.05)
dev.off()

## save result
moduleLabels = net$colors
moduleColors = labels2colors(net$colors)
# table(moduleColors)

# # recalculate module eigengenes by color
MEs0 = moduleEigengenes(datExpr2, moduleColors)$eigengenes
MEs = orderMEs(MEs0)

geneTree = net$dendrograms[[1]]

cat("\nNumber of genes in each module: \n")
print(as.data.frame(table(moduleColors)))

# find the top hub gene in each module
cat("\nTOP hub gene in each module: \n")
topHubs <- chooseTopHubInEachModule(datExpr=datExpr2, colorh = moduleColors, power = 2)
print(topHubs)



#################### test module - traits correlation #################
cat("\n_-------- Calculate Modules - traits correlation -------------\n")
cor <- stats::cor
moduleTraitCor = cor(MEs, datTraits, use = "p");
moduleTraitPvalue = corPvalueStudent(moduleTraitCor, nrow(datExpr2))

textMatrix =  paste(signif(moduleTraitCor, 2), "\n(",
                    signif(moduleTraitPvalue, 1), ")", sep = "")
dim(textMatrix) = dim(moduleTraitCor)

# png("Part3_ModuleTraitCorrelation.png", width=1000, height=500)
# par(mar = c(3, 10, 3, 3))
# labeledHeatmap(Matrix = moduleTraitCor,
#                xLabels = names(datTraits),
#                yLabels = names(MEs),
#                ySymbols = names(MEs),
#                colorLabels = FALSE,
#                colors = blueWhiteRed(50),
#                textMatrix = textMatrix,
#                setStdMargins = FALSE,
#                cex.text = 0.8,
#                zlim = c(-1,1),
#                main = paste("Module-trait relationships"))

pdf("Part3_ModuleTraitCorrelation.pdf", width=12, height=8)
par(mar = c(3, 10, 3, 3))
labeledHeatmap(Matrix = moduleTraitCor,
               xLabels = names(datTraits),
               yLabels = names(MEs),
               ySymbols = names(MEs),
               colorLabels = FALSE,
               colors = greenWhiteRed(50),
               textMatrix = textMatrix,
               setStdMargins = FALSE,
               cex.text = 0.5,
               zlim = c(-1,1),
               main = paste("Module-trait relationships"))
dev.off()


# save WGCNA data
save(datExpr2, datTraits, MEs, moduleLabels, moduleColors, geneTree, 
     file = "network.RData")
write.table(datExpr2, quote=FALSE, file="WGCNA_expressionData.tsv", col.names=NA, sep="\t")
write.table(datTraits, quote=FALSE, file="WGCNA_traitData.tsv", col.names=NA, sep="\t")
write.table(MEs, quote=FALSE, file="WGCNA_moduleEigengenes.tsv", col.names=NA, sep="\t")

cat("\n--------------------- Part3 Done -----------------------------\n")
